server:
  port: 8080

spring:
  application:
    name: 'Loja'

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
     
fornecedor:
    url: http://fornecedor/api/v1/fornecedor/info/SP