
server:
  port: 8083

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: D:\workarea\projetos\mocroservice-repositorio-config-server